/*
 * Copyright (C) 2017 taylor.fish <contact@taylor.fish>
 *
 * This file is part of Fish Waveshaper.
 *
 * Fish Waveshaper is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Fish Waveshaper is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Fish Waveshaper.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was automatically generated by generate_plugin_data.py.

#ifndef PORTS_H
#define PORTS_H

enum {
    NUM_USER_POINTS = 6,
    PORT_END_POINT_Y = 0,
    MIN_ORIGIN_PORT = 1,
    MAX_ORIGIN_PORT = 4,
    MIN_POINT_PORT = 5,
    MAX_POINT_PORT = 40,
    MIN_ASYM_PORT = 41,
    MAX_ASYM_PORT = 45,
    PORT_INPUT_L = 46,
    PORT_OUTPUT_L = 47,
    PORT_INPUT_R = 48,
    PORT_OUTPUT_R = 49,
    PORT_OVERSAMPLE = 50,
    PORT_INPUT_GAIN = 51,
    PORT_OUTPUT_GAIN = 52,
    PORT_DISPLAY_PLOT = 53,
    PORT_MONITOR_LEVELS = 54,
    PORT_ASYMMETRIC = 55,
    PORT_INPUT_LEVEL = 56,
    PORT_INPUT_CLIP = 57,
    PORT_OUTPUT_LEVEL = 58,
    PORT_OUTPUT_0DB = 59,
};

#endif
